export const cats = {
  Shadow: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [
      ["band", "head"],
      ["sunglasses", "eye"],
      ["scarf", "neck"],
      ["umbrella", "hand"],
    ],
    xScale: "1.260",
    yScale: "0.786",
  },
  Midnight: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [["bow", "head"]],
    xScale: "1.041",
    yScale: "0.816",
  },
  Salem: {
    color: "black",
    patterns: [],
    accessories: [
      ["band", "head"],
      ["scarf", "neck"],
    ],
    xScale: "1.165",
    yScale: "0.987",
  },
  Jinx: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [["scarf", "neck"]],
    xScale: "1.217",
    yScale: "0.836",
  },
  Inky: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [
      ["cap", "head"],
      ["bowtie", "neck"],
    ],
    xScale: "0.769",
    yScale: "1.269",
  },
  Velvet: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [
      ["cap", "head"],
      ["glasses", "eye"],
      ["scarf", "neck"],
    ],
    xScale: "0.818",
    yScale: "1.286",
  },
  Smudge: {
    color: "black",
    patterns: [],
    accessories: [
      ["beanie", "head"],
      ["sunglasses", "eye"],
      ["scarf", "neck"],
    ],
    xScale: "0.982",
    yScale: "0.856",
  },
  Echo: {
    color: "black",
    patterns: [],
    accessories: [
      ["hat", "head"],
      ["bowtie", "neck"],
    ],
    xScale: "1.092",
    yScale: "1.019",
  },
  Loki: {
    color: "black",
    patterns: ["tuxedo"],
    accessories: [["scarf", "neck"]],
    xScale: "1.150",
    yScale: "0.724",
  },
  Nyx: {
    color: "black",
    patterns: [],
    accessories: [
      ["band", "head"],
      ["umbrella", "hand"],
    ],
    xScale: "1.248",
    yScale: "1.025",
  },
  Ginger: {
    color: "orange",
    patterns: ["tuxedo"],
    accessories: [
      ["glasses", "eye"],
      ["tie", "neck"],
    ],
    xScale: "1.103",
    yScale: "0.769",
  },
  Simba: {
    color: "orange",
    patterns: ["tuxedo"],
    accessories: [["hat", "head"]],
    xScale: "0.701",
    yScale: "1.187",
  },
  Nala: {
    color: "orange",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["band", "head"],
      ["sunglasses", "eye"],
      ["tie", "neck"],
    ],
    xScale: "0.864",
    yScale: "0.731",
  },
  Tigger: {
    color: "orange",
    patterns: ["tabby"],
    accessories: [["beanie", "head"]],
    xScale: "0.912",
    yScale: "1.065",
  },
  Tiger: {
    color: "orange",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["cap", "head"],
      ["scarf", "neck"],
    ],
    xScale: "1.066",
    yScale: "0.783",
  },
  Honey: {
    color: "orange",
    patterns: ["tuxedo"],
    accessories: [["cane", "hand"]],
    xScale: "0.766",
    yScale: "0.719",
  },
  Maple: {
    color: "orange",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["hat", "head"],
      ["bag", "hand"],
    ],
    xScale: "0.852",
    yScale: "0.703",
  },
  Peaches: {
    color: "orange",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["beanie", "head"],
      ["glasses", "eye"],
      ["cane", "hand"],
    ],
    xScale: "1.250",
    yScale: "1.052",
  },
  Marmalade: {
    color: "orange",
    patterns: [],
    accessories: [["tie", "neck"]],
    xScale: "1.273",
    yScale: "0.943",
  },
  Apollo: {
    color: "orange",
    patterns: [],
    accessories: [],
    xScale: "1.102",
    yScale: "0.959",
  },
  Mochi: {
    color: "cream",
    patterns: ["tuxedo"],
    accessories: [
      ["sunglasses", "eye"],
      ["umbrella", "hand"],
    ],
    xScale: "0.887",
    yScale: "0.976",
  },
  Miso: {
    color: "cream",
    patterns: ["tuxedo"],
    accessories: [
      ["band", "head"],
      ["tie", "neck"],
      ["bag", "hand"],
    ],
    xScale: "1.259",
    yScale: "1.187",
  },
  Pudding: {
    color: "cream",
    patterns: ["tuxedo", "tabby"],
    accessories: [["beanie", "head"]],
    xScale: "0.959",
    yScale: "0.839",
  },
  Cookie: {
    color: "cream",
    patterns: ["tuxedo"],
    accessories: [["bowtie", "neck"]],
    xScale: "1.120",
    yScale: "1.273",
  },
  Muffin: {
    color: "cream",
    patterns: ["tuxedo", "tabby"],
    accessories: [],
    xScale: "0.733",
    yScale: "1.217",
  },
  Biscuit: {
    color: "cream",
    patterns: ["tabby"],
    accessories: [
      ["cap", "head"],
      ["glasses", "eye"],
    ],
    xScale: "0.807",
    yScale: "0.724",
  },
  Latte: {
    color: "cream",
    patterns: ["tabby"],
    accessories: [["sunglasses", "eye"]],
    xScale: "0.737",
    yScale: "0.944",
  },
  Waffle: {
    color: "cream",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["glasses", "eye"],
      ["bowtie", "neck"],
    ],
    xScale: "1.061",
    yScale: "0.802",
  },
  Tofu: {
    color: "cream",
    patterns: ["tabby"],
    accessories: [
      ["beanie", "head"],
      ["glasses", "eye"],
    ],
    xScale: "0.837",
    yScale: "1.075",
  },
  Pickles: {
    color: "cream",
    patterns: [],
    accessories: [
      ["glasses", "eye"],
      ["bowtie", "neck"],
    ],
    xScale: "0.714",
    yScale: "0.913",
  },
  Smokey: {
    color: "gray",
    patterns: ["tabby"],
    accessories: [
      ["bow", "head"],
      ["glasses", "eye"],
    ],
    xScale: "1.020",
    yScale: "0.701",
  },
  Ash: {
    color: "gray",
    patterns: ["tabby"],
    accessories: [
      ["cap", "head"],
      ["glasses", "eye"],
    ],
    xScale: "1.075",
    yScale: "1.051",
  },
  Cinder: {
    color: "gray",
    patterns: [],
    accessories: [["beanie", "head"]],
    xScale: "0.784",
    yScale: "0.918",
  },
  Slate: {
    color: "gray",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["beanie", "head"],
      ["bowtie", "neck"],
    ],
    xScale: "1.264",
    yScale: "1.149",
  },
  Charcoal: {
    color: "gray",
    patterns: ["tabby"],
    accessories: [
      ["beanie", "head"],
      ["bowtie", "neck"],
    ],
    xScale: "1.225",
    yScale: "1.251",
  },
  Pebbles: {
    color: "gray",
    patterns: ["tabby"],
    accessories: [
      ["cap", "head"],
      ["glasses", "eye"],
      ["tie", "neck"],
      ["bag", "hand"],
    ],
    xScale: "0.975",
    yScale: "0.824",
  },
  Dusty: {
    color: "gray",
    patterns: ["tuxedo", "tabby"],
    accessories: [["band", "head"]],
    xScale: "0.958",
    yScale: "0.809",
  },
  Steel: {
    color: "gray",
    patterns: ["tuxedo"],
    accessories: [
      ["hat", "head"],
      ["glasses", "eye"],
    ],
    xScale: "1.002",
    yScale: "1.248",
  },
  Graphite: {
    color: "gray",
    patterns: ["tuxedo", "tabby"],
    accessories: [
      ["hat", "head"],
      ["bag", "hand"],
    ],
    xScale: "1.145",
    yScale: "0.790",
  },
  Fog: {
    color: "gray",
    patterns: ["tuxedo", "tabby"],
    accessories: [],
    xScale: "1.122",
    yScale: "1.199",
  },
  Snowball: {
    color: "white",
    patterns: [],
    accessories: [
      ["sunglasses", "eye"],
      ["bag", "hand"],
    ],
    xScale: "1.235",
    yScale: "0.797",
  },
  Ivory: {
    color: "white",
    patterns: [],
    accessories: [["glasses", "eye"]],
    xScale: "0.992",
    yScale: "0.898",
  },
  Pearl: {
    color: "white",
    patterns: [],
    accessories: [
      ["glasses", "eye"],
      ["bag", "hand"],
    ],
    xScale: "0.905",
    yScale: "0.763",
  },
  Cotton: {
    color: "white",
    patterns: [],
    accessories: [
      ["beanie", "head"],
      ["glasses", "eye"],
    ],
    xScale: "1.239",
    yScale: "1.064",
  },
  Lily: {
    color: "white",
    patterns: [],
    accessories: [["hat", "head"]],
    xScale: "1.287",
    yScale: "0.710",
  },
  Blizzard: {
    color: "white",
    patterns: [],
    accessories: [["bow", "head"]],
    xScale: "1.298",
    yScale: "0.990",
  },
  Marshmallow: {
    color: "white",
    patterns: [],
    accessories: [
      ["band", "head"],
      ["glasses", "eye"],
      ["bowtie", "neck"],
    ],
    xScale: "1.197",
    yScale: "0.761",
  },
  Ghost: {
    color: "white",
    patterns: [],
    accessories: [
      ["cap", "head"],
      ["tie", "neck"],
      ["balloon", "hand"],
    ],
    xScale: "0.949",
    yScale: "1.013",
  },
  Daisy: {
    color: "white",
    patterns: [],
    accessories: [],
    xScale: "1.129",
    yScale: "0.858",
  },
  Casper: {
    color: "white",
    patterns: [],
    accessories: [
      ["cap", "head"],
      ["glasses", "eye"],
    ],
    xScale: "0.904",
    yScale: "1.111",
  },
};
